version: '3'
services:
  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - .:/app
    tty: true
    depends_on:
      - api
#
#  frontend:
#    container_name: frontend
#    build:
#      context: ./docker/frontend
#      dockerfile: Dockerfile
#    environment:
#      PORT: '3000'
#      HOST: '0.0.0.0'
#      BASE_URL: 'http://localhost'
#      API_URL: 'http://localhost/api/v1'
#    ports:
#      - 3000:3000
#    volumes:
#      - sync_spa_sample:/app
#    stdin_open: true
#    tty: true
#    restart: always
#    depends_on:
#      - backend

  api:
    container_name: api
    build:
      context: ./docker/api
      dockerfile: Dockerfile
    environment:
      LANG: 'ja_JP.UTF-8'
      TZ: 'Asia/Tokyo'
    volumes:
      - .:/app
    expose:
      - 9000
    tty: true
